### ISSUE TITLE
Tardis Plugin Spam (Was fixed on Paper)

### ISSUE THREAD

**Issue by waddon1** [pl3xgaming/Purpur#413]
Not a crash

## Expected behavior
 The server not being spammed
https://pastebin.com/RbUzTw0L

## Observed/Actual behavior
 Server console is being spammed.

## Steps/models to reproduce
Use Pupur and Tardis plugin instead of paper.

## Purpur version

25.06 15:00:05 [Server] INFO This server is running Purpur version git-Purpur-1191 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: bdcea0e on HEAD)
25.06 15:00:05 [Server] INFO You are running the latest version
25.06 15:00:05 [Server] INFO Previous version: git-Purpur-1187 (MC: 1.17)

## Agreements
Please agree to the following.
- [ -] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [ -] I have searched for and ensured there isn't already an open issue regarding this.
- [ -] My version of Minecraft is supported by Purpur.

## Other
 This was fixed a few days in Paper but not in Purpur for some reason

**Comment by waddon1** [comment]
Was fixed as part of this issue https://github.com/PaperMC/paperweight/issues/24

**Comment by BillyGalbreath** [comment]
This issue is already being tracked upstream. It is a mappings issue in the paperweight build tool. They have not fixed it, yet.

https://github.com/PaperMC/paperweight/issues/24

https://github.com/PaperMC/paperweight/issues/45
